### ISSUE TITLE
Plugin issue with compiling

### ISSUE THREAD

**Issue by Optifyne** [TheCymaera/minecraft-spider#18]
Hello, I wanted to change the code a bit, but when I compiled code even without any changes, after it on the server I see this error when trying to click to netherite ingot for spawn spider. Everything else seems to be OK, except this. I do not know nothing about the Kotlin or plugin development, although I tried to find the issue myself, but I do not understand, sorry. I have PurPur 1.21.1. Thank you.

`[11:55:33 ERROR]: Could not pass event PlayerInteractEvent to spider-animation v2.1-SNAPSHOT
java.lang.NullPointerException: Cannot invoke "org.bukkit.util.Vector.clone()" because the return value of "com.heledron.spideranimation.spider.LegPlan.getRestPosition()" is null
        at SpiderAnimation-2.1-SNAPSHOT.jar/com.heledron.spideranimation.spider.Leg.restPosition(SpiderBody.kt:197) ~[SpiderAnimation-2.1-SNAPSHOT.jar:?]
        at SpiderAnimation-2.1-SNAPSHOT.jar/com.heledron.spideranimation.spider.Leg.<init>(SpiderBody.kt:32) ~[SpiderAnimation-2.1-SNAPSHOT.jar:?]
        at SpiderAnimation-2.1-SNAPSHOT.jar/com.heledron.spideranimation.spider.SpiderBody.<init>(SpiderBody.kt:307) ~[SpiderAnimation-2.1-SNAPSHOT.jar:?]
        at SpiderAnimation-2.1-SNAPSHOT.jar/com.heledron.spideranimation.spider.Spider.<init>(Spider.kt:126) ~[SpiderAnimation-2.1-SNAPSHOT.jar:?]
        at SpiderAnimation-2.1-SNAPSHOT.jar/com.heledron.spideranimation.AppState.createSpider(AppState.kt:33) ~[SpiderAnimation-2.1-SNAPSHOT.jar:?]
        at SpiderAnimation-2.1-SNAPSHOT.jar/com.heledron.spideranimation.RegisterItemsKt.registerItems$lambda$0(registerItems.kt:29) ~[SpiderAnimation-2.1-SNAPSHOT.jar:?]
        at SpiderAnimation-2.1-SNAPSHOT.jar/com.heledron.spideranimation.utilities.CustomItemRegistry._init_$lambda$1(CustomItem.kt:45) ~[SpiderAnimation-2.1-SNAPSHOT.jar:?]
        at SpiderAnimation-2.1-SNAPSHOT.jar/com.heledron.spideranimation.utilities.UtilitiesKt$onGestureUseItem$1.onPlayerInteract(utilities.kt:73) ~[SpiderAnimation-2.1-SNAPSHOT.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor817.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2297-ef12ede]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:604) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:538) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:2020) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:44) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:11) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1574) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1551) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1544) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1503) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1510) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1355) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`

**Comment by TheCymaera** [comment]
Hi. Few questions:

How did you compile?

Do you have the same issues with the pre-compiled JARs on the release page?

Did you use the original JAR, or the one bundled with Kotlin? (If the former, did you make sure to install Kotlin separately?)

**Comment by TheCymaera** [comment]
Try deleting the configuration file.

If you installed the latest release previously, there may be incompatibilities with the configuration file.

**Comment by TheCymaera** [comment]
It should be located in a child folder inside the `plugins` folder.

**Comment by Optifyne** [comment]
Thank you, it works)
