### ISSUE TITLE
Error while enabling the plugin

### ISSUE THREAD

**Issue by kimoVoid** [TheCymaera/minecraft-spider#3]
The plugin isn't loading on the latest paper 1.20.4. I'm using java 17 on windows, and there are no other plugins.

```
[10:43:49 INFO]: [spider-animation] Enabling spider-animation v1.0-SNAPSHOT
[10:43:49 INFO]: [spider-animation] SpiderAnimation plugin enabled
[10:43:49 ERROR]: Error occurred while enabling spider-animation v1.0-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: null
        at com.heledron.spideranimation.SpiderAnimationPlugin.onEnable(SpiderAnimationPlugin.kt:20) ~[SpiderAnimation-1.0-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-461]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-461]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-461]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-461]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-461]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-461]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-461]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-461]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-461]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:43:49 INFO]: [spider-animation] Disabling spider-animation v1.0-SNAPSHOT
```

**Comment by Lolbiq** [comment]
I figured out that the problem is in mismatching of versions of PaperMC server and of Spider-Animation plugin. But that's not so hard to get thou. I guess it'd be easier if author would have mentioned the version of minecraft on which he has done his project. I think the task to fix this is very easy for the developer. He just gave us the source code, but he didn't think that random players would be interested in it, or didn't think that not everybody understands how all this stuff works. For him it's easy, and he might think: "Ok, i gave 'em all what they need". And that is true. But how to use it? XD

**Comment by wordandahalf** [comment]
> I figured out that the problem is in mismatching of versions of PaperMC server and of Spider-Animation plugin. But that's not so hard to get thou. I guess it'd be easier if author would have mentioned the version of minecraft on which he has done his project. I think the task to fix this is very easy for the developer. He just gave us the source code, but he didn't think that random players would be interested in it, or didn't think that not everybody understands how all this stuff works. For him it's easy, and he might think: "Ok, i gave 'em all what they need". And that is true. But how to use it? XD

Perhaps it's not the author's responsibility to cater to non-technical users. The error you encountered has nothing to do with the version of the server, [it indicates that it couldn't find a `world`](https://github.com/TheCymaera/minecraft-spider/blame/fd9133800cf3e65181db294b4cfa582d8d058dac/src/main/java/com/heledron/spideranimation/SpiderAnimationPlugin.kt#L20). And, you could very easily find the necessary server version by [searching for "version" in the repo](https://github.com/search?q=repo%3ATheCymaera%2Fminecraft-spider%20version&type=code).

**Comment by TheCymaera** [comment]
> I figured out that the problem is in mismatching of versions of PaperMC server and of Spider-Animation plugin. But that's not so hard to get thou. I guess it'd be easier if author would have mentioned the version of minecraft on which he has done his project. I think the task to fix this is very easy for the developer. He just gave us the source code, but he didn't think that random players would be interested in it, or didn't think that not everybody understands how all this stuff works. For him it's easy, and he might think: "Ok, i gave 'em all what they need". And that is true. But how to use it? XD

I've added a README. Let me know if there's anything else you think should be clarified.
